// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcpelfllyutpkystubxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjcGVsZmxseXV0cGt5c3R1YnhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjA3ODcsImV4cCI6MjA3MTY5Njc4N30.AqPrD2Fa7P0225JQI5Um2hT0_bAoi9J30_QvUSBkcUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});